# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='credibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faqs',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='guarantee',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headline_sub',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='price',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='problem_sub',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_proof',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='solution_benefit_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='solution_benefit_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='solution_benefit_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='solution_sub',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=models.TextField(blank=True),
        ),
    ]
