# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161213_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='credibility',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headline',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='problem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='problem_sub',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_proof',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='solution',
            field=models.TextField(),
        ),
    ]
