# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161213_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('benefit', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='solution_benefit_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='solution_benefit_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='solution_benefit_3',
        ),
        migrations.AddField(
            model_name='homepagebenefits',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='home.HomePage'),
        ),
    ]
