# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20161213_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebenefits',
            name='benefit',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
