# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161213_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebenefits',
            name='benefit',
        ),
        migrations.AddField(
            model_name='homepagebenefits',
            name='copy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagebenefits',
            name='heading',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
