# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20161213_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebenefits',
            name='icon_classname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
