# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepagebenefits_icon_classname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagebenefits',
            old_name='heading',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='homepagebenefits',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_benefits', to='home.HomePage'),
        ),
    ]
