# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20161213_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='credibility',
            field=models.TextField(help_text='Tie your company to trusted symbols and famous authorities.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta',
            field=models.TextField(blank=True, help_text='Tell the customer to do something, such as asking for money (without guilt).'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='faqs',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Boost your conversions by as much as 85% with an FAQ!'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='guarantee',
            field=models.TextField(blank=True, help_text="Think guarantee's, but you're really just reducing fear."),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headline',
            field=models.TextField(help_text='End Result Customer Wants + Specific Period Of Time + Address The Objections'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='price',
            field=models.TextField(blank=True, help_text='Make your price seem like a bargain'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='problem',
            field=models.TextField(help_text='Explain the problem using your customers words'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_proof',
            field=models.TextField(help_text='Show people are using your stuff and signing up'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='solution',
            field=models.TextField(help_text='Product Name Helps You Do [Task]. Say Goodbye To [Frustration] And Hello To [Benefit]. You Get [Top 3 Features + Benefits For Each Feature]'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonials',
            field=models.TextField(blank=True, help_text='Proof your product works in your customers’ words. – Specific end result or benefit customer got + Specific Period of time + Accompanied Feeling + The Persons Name With Their Stats'),
        ),
        migrations.AlterField(
            model_name='homepagebenefits',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
