# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 21:18
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20161213_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='solution_sub',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='solution',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Product Name Helps You Do [Task]. Say Goodbye To [Frustration] And Hello To [Benefit]. You Get [Top 3 Features + Benefits For Each Feature]'),
        ),
    ]
