# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 21:26
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20161213_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='problem_sub',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='problem',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Explain the problem using your customers words'),
        ),
    ]
