# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 21:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20161213_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='credibility',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Tie your company to trusted symbols and famous authorities.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_proof',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Show people are using your stuff and signing up'),
        ),
    ]
