# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20161213_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTestimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('avatarURL', models.URLField()),
                ('quote', wagtail.wagtailcore.fields.RichTextField()),
                ('person', wagtail.wagtailcore.fields.RichTextField()),
                ('profileURL', models.URLField()),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials',
        ),
        migrations.AddField(
            model_name='homepagetestimonials',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.HomePage'),
        ),
    ]
