# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20161213_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetestimonials',
            name='person',
            field=models.TextField(),
        ),
    ]
