# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 03:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20161213_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetestimonials',
            name='quote',
            field=wagtail.wagtailcore.fields.RichTextField(help_text='Specific end result or benefit customer got + Specific Period of time + Accompanied Feeling + The Persons Name With Their Stats'),
        ),
    ]
