# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 01:16
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20161214_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='headline_sub',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
