# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 03:26
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20161219_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cta',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.TextBlock()), ('subtitle', wagtail.wagtailcore.blocks.RichTextBlock(blank=True))), icon='title')), ('actions', wagtail.wagtailcore.blocks.StreamBlock((('link', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock()), ('url', wagtail.wagtailcore.blocks.CharBlock()), ('icon', wagtail.wagtailcore.blocks.CharBlock(help_text='Optional: FontAwesome icon classname', max_length=50, required=False)), ('target_blank', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Open link in a new tab?', required=False))), icon='link')), ('doc', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.CharBlock()), ('doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('icon', wagtail.wagtailcore.blocks.CharBlock(help_text='Optional: FontAwesome icon classname', max_length=50, required=False)), ('target_blank', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Open link in a new tab?', required=False))), icon='doc-empty'))))))),
        ),
    ]
